/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as AuthenticatedAncestryRouteImport } from './routes/_authenticated/ancestry'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAncestryRoute = AuthenticatedAncestryRouteImport.update({
  id: '/ancestry',
  path: '/ancestry',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ancestry': typeof AuthenticatedAncestryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ancestry': typeof AuthenticatedAncestryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ancestry': typeof AuthenticatedAncestryRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/ancestry' | '/wiki/$slug' | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/ancestry' | '/wiki/$slug' | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ancestry'
    | '/wiki/$slug'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  WikiSlugRoute: typeof WikiSlugRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ancestry': {
      id: '/_authenticated/ancestry'
      path: '/ancestry'
      fullPath: '/ancestry'
      preLoaderRoute: typeof AuthenticatedAncestryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAncestryRoute: typeof AuthenticatedAncestryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAncestryRoute: AuthenticatedAncestryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  WikiSlugRoute: WikiSlugRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
